# Generated by Django 4.1.5 on 2023-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("seasons", models.IntegerField()),
                ("review", models.TextField(max_length=255)),
                ("genre", models.CharField(max_length=20)),
            ],
        ),
    ]
