# Generated by Django 4.1.5 on 2023-01-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0002_series"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Series",
        ),
    ]
