# Generated by Django 4.1 on 2023-01-04 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("watchlist", "0006_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="created",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="updated",
            new_name="updated_on",
        ),
        migrations.RenameField(
            model_name="watchlist",
            old_name="created",
            new_name="created_on",
        ),
        migrations.AddField(
            model_name="review",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
