# Generated by Django 4.1.5 on 2023-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0007_rename_created_review_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="number_rating",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
